### ISSUE TITLE
Split config file into multiple config files or a dotenv file

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/road-to-legend-server#104]
This is probably only needed for development, but one issue I get a lot is that when the source code changes, there's a chance that new variables are added/moved/removed from the config file, which means updating to the latest version of the game forces you to manually update your config files (as they are not migrated).

Splitting the more sensitive and static variables out of the main config file (maybe into a dotenv file as well) would help avoid conflicts when updating.

**Comment by MrEliasen** [comment]
Fixed in version 0.1.0 (https://github.com/MrEliasen/path-to-power/commit/5ed4d04a17a0d663fe66e1f40840144ff69660a2)

Moved sensitive information to .env file
